language: rust
rust:
  - 1.1.0
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo doc
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo test --verbose;
      cargo bench --verbose;
    fi
