[package]
name = "qsv"
version = "0.16.2"  #:version
authors = ["Joel Natividad <joel@datHere.com>"]
description = "A high performance CSV command line toolkit forked from xsv."
documentation = "https://github.com/jqnatividad/qsv"
homepage = "https://github.com/jqnatividad/qsv"
repository = "https://github.com/jqnatividad/qsv"
readme = "README.md"
keywords = ["csv", "tsv", "slice", "command"]
license = "Unlicense/MIT"
autotests = false
edition = "2018"

[[bin]]
name = "qsv"
test = false
bench = false
doctest = false

[[test]]
name = "tests"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
debug = true

[profile.test]
opt-level = 3

[dependencies]
mimalloc = { version = "0.1.26", default-features = false }
byteorder = "1.4"
crossbeam-channel = "0.5"
csv = "1.1"
csv-index = "0.1"
docopt = "1"
filetime = "0.2"
hlua = "0.4.1"
num_cpus = "1"
rand = "0.7"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
streaming-stats = "0.2"
tabwriter = "1.2"
textwrap = "0.14.0"
threadpool = "1.8"
dateparser = "0.1.5"
uuid = { version = "0.8.1", features = ["v4"] }

[build-dependencies]
rustc_version = "0.4"

[dev-dependencies]
quickcheck = { version = "0.9", default-features = false }
log = "0.4"

