[package]
name = "xsv"
version = "0.12.2"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "A high performance CSV command line toolkit."
documentation = "http://burntsushi.net/rustdoc/xsv/"
homepage = "https://github.com/BurntSushi/xsv"
repository = "https://github.com/BurntSushi/xsv"
readme = "README.md"
keywords = ["csv", "tsv", "slice", "command"]
license = "Unlicense/MIT"

[[bin]]
name = "xsv"
test = false
bench = false
doctest = false

[[test]]
name = "tests"

[profile.release]
opt-level = 3
debug = true

[profile.test]
opt-level = 3

[dependencies]
byteorder = "1"
chan = "0.1"
csv = "1.0.0-beta.5"
csv-index = "0.1.3"
docopt = "0.8"
filetime = "0.1"
num_cpus = "1.4"
rand = "0.4"
regex = "0.2"
serde = "1"
serde_derive = "1"
streaming-stats = "0.2"
tabwriter = "1"
threadpool = "1.3"

[dev-dependencies]
quickcheck = { version = "0.6", default-features = false }
log = "0.4"
