[package]
name = "xsv"
version = "0.3.0"
authors = ["Andrew Gallant <jamslam@gmail.com>"]

[dependencies.rust-csv]
git = "git://github.com/BurntSushi/rust-csv"
# path = "/home/andrew/data/projects/rust/rust-csv" 

[dependencies.rust-stats]
# path = "/home/andrew/data/projects/rust-stats" 
git = "git://github.com/BurntSushi/rust-stats"

[dependencies.tabwriter]
git = "git://github.com/BurntSushi/tabwriter"

[dependencies.docopt] 
git = "git://github.com/docopt/docopt.rs"
# path = "/home/andrew/data/projects/rust/docopt.rs"

[dev-dependencies.quickcheck]
git = "git://github.com/BurntSushi/quickcheck"

[[bin]]
name = "xsv"
test = false

[[test]]
name = "tests"
