[package]
name = "qsv"
version = "0.14.0"  #:version
authors = ["Joel Natividad <joel@datHere.com>"]
description = "A high performance CSV command line toolkit forked from xsv."
documentation = "https://github.com/jqnatividad/qsv"
homepage = "https://github.com/jqnatividad/qsv"
repository = "https://github.com/jqnatividad/qsv"
readme = "README.md"
keywords = ["csv", "tsv", "slice", "command"]
license = "Unlicense/MIT"
autotests = false

[[bin]]
name = "qsv"
test = false
bench = false
doctest = false

[[test]]
name = "tests"

[profile.release]
opt-level = 3
debug = true

[profile.test]
opt-level = 3

[dependencies]
byteorder = "1"
crossbeam-channel = "0.2.4"
csv = "1.1.0"
csv-index = "0.1.6"
docopt = "1"
filetime = "0.1"
num_cpus = "1.4"
rand = "0.5"
regex = "1"
serde = "1"
serde_derive = "1"
streaming-stats = "0.2.3"
tabwriter = "1"
threadpool = "1.3"

[dev-dependencies]
quickcheck = { version = "0.7", default-features = false }
log = "0.4"
