[package]
name = "qsv"
version = "0.14.1"  #:version
authors = ["Joel Natividad <joel@datHere.com>"]
description = "A high performance CSV command line toolkit forked from xsv."
documentation = "https://github.com/jqnatividad/qsv"
homepage = "https://github.com/jqnatividad/qsv"
repository = "https://github.com/jqnatividad/qsv"
readme = "README.md"
keywords = ["csv", "tsv", "slice", "command"]
license = "Unlicense/MIT"
autotests = false
edition = "2018"

[[bin]]
name = "qsv"
test = false
bench = false
doctest = false

[[test]]
name = "tests"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
debug = true

[profile.test]
opt-level = 3

[dependencies]
mimalloc = { version = "*", default-features = false }
byteorder = "1.4"
crossbeam-channel = "0.5"
csv = "1.1.0"
csv-index = "0.1.6"
docopt = "1"
filetime = "0.2"
num_cpus = "1"
rand = "0.7"
regex = "1"
serde = { version = "1.0.130", features = ["derive"] }
streaming-stats = "0.2.3"
tabwriter = "1"
threadpool = "1.8"

[dev-dependencies]
quickcheck = { version = "0.9", default-features = false }
log = "0.4"
