[package]
name = "qsv"
version = "0.27.1"  #:version
authors = ["Joel Natividad <joel@datHere.com>"]
description = "A high performance CSV command line toolkit."
documentation = "https://docs.rs/crate/qsv"
homepage = "https://github.com/jqnatividad/qsv"
repository = "https://github.com/jqnatividad/qsv"
readme = "README.md"
keywords = ["csv", "geocode", "slice", "cli", "opendata"]
categories = ["command-line-utilities"]
license = "MIT OR Unlicense"
autotests = false
edition = "2021"
rust-version = "1.56"
autobins = false

[[bin]]
name = "qsv"
test = false
bench = false
doctest = false
path = "src/main.rs"

[[bin]]
name = "qsvlite"
test = false
bench = false
doctest = false
path = "src/mainlite.rs"

[[test]]
name = "tests"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = false

[profile.test]
opt-level = 3

[dependencies]
mimalloc = { version = "0.1.27", default-features = false, optional = true }
byteorder = "1.4"
crossbeam-channel = "0.5"
csv = "1.1"
csv-index = "0.1"
docopt = "1"
filetime = "0.2"
hlua = { version = "0.4.1", optional = true }
num_cpus = "1"
rand = "0.8"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
qsv-stats = "0.3"
tabwriter = "1.2"
threadpool = "1.8"
chrono = { version = "0.4", optional = true }
dateparser = "0.1.6"
once_cell = { version = "1.9", optional = true }
reverse_geocoder = { version = "2", optional = true }
qsv_currency = { version = "0.5", optional = true }
itertools = "0.10"
strsim = { version = "0.10", optional = true }
eudex = { version = "0.1.1", optional = true }
indicatif = "0.16"
thousands = "0.2"
titlecase = { version = "1", optional = true }
censor = { version = "0.2", optional = true }
cached = { version = "0.26", default-features = false, features = ["proc_macro"] }
uuid = { version = "0.8.2", features = ["v4"] }
test-data-generation = { version = "0.3", optional = true }
self_update = { version = "0.28", features = ["archive-zip", "compression-zip-deflate", "rustls"], default-features = false }
log = "0.4.14"
flexi_logger = { version = "0.22", features = ["compress"] }
vader_sentiment = { version = "0.1.1", optional = true }
whatlang = { version = "0.12.0", optional = true }
reqwest = { version = "0.11", features = ["blocking", "json", "rustls-tls"], default-features = false }
jql = { version = "3.0.6", default-features = false }
pyo3 = { version = "0.15.1", features = ["auto-initialize"], optional = true }

[dev-dependencies]
quickcheck = { version = "1", default-features = false }

[features]
default = ["mimalloc"]
lua = ["hlua"]
foreach = []
apply = ["qsv_currency", "eudex", "titlecase", "censor", "strsim", 
         "reverse_geocoder", "once_cell", "chrono", "vader_sentiment", "whatlang"]
generate = ["test-data-generation"]
python = ["pyo3"]
