[package]
name          = "qsv"
version       = "0.42.0"                                                  #:version
authors       = ["Joel Natividad <joel@datHere.com>"]
description   = "A high performance CSV command line toolkit."
documentation = "https://github.com/jqnatividad/qsv"
homepage      = "https://github.com/jqnatividad/qsv"
repository    = "https://github.com/jqnatividad/qsv"
readme        = "README.md"
keywords      = ["csv", "geocode", "data-engineering", "cli", "opendata"]
categories    = ["command-line-utilities", "parser-implementations"]
license       = "MIT OR Unlicense"
autotests     = false
edition       = "2021"
rust-version  = "1.60.0"
autobins      = false
include       = ["src/**/*", "LICENSE-MIT", "README.md", "CHANGELOG.md"]

[[bin]]
name    = "qsv"
test    = false
bench   = false
doctest = false
path    = "src/main.rs"

[[bin]]
name              = "qsvlite"
test              = false
bench             = false
doctest           = false
path              = "src/mainlite.rs"
required-features = ["lite"]

[[test]]
name = "tests"
path = "tests/tests.rs"

[profile.release]
codegen-units = 1
debug         = false
lto           = true
opt-level     = 3
strip         = true

[profile.test]
opt-level = 3

[dependencies]
ahash = "0.7"
anyhow = "1.0"
byteorder = "1.4"
cached = { version = "0.34", default-features = false, features = [
    "proc_macro",
    "redis_store",
], optional = true }
calamine = "0.18"
censor = { version = "0.2", optional = true }
chrono = { version = "0.4", optional = true }
crossbeam-channel = "0.5"
csv = "1.1"
csv-core = "0.1"
csv-index = "0.1"
csv-sniffer = "0.3"
docopt = "1"
dynfmt = { version = "0.1", default-features = false, features = [
    "curly",
], optional = true }
eudex = { version = "0.1", optional = true }
filetime = "0.2"
flexi_logger = { version = "0.22", features = [
    "compress",
], default-features = false }
governor = { version = "0.4", optional = true }
grex = { version = "1.4.0-SNAPSHOT", default-features = false }
indicatif = "0.16"
itertools = "0.10"
itoa = "1"
jsonschema = { version = "0.16", features = [
    "resolve-file",
    "resolve-http",
], default-features = false }
jsonxf = { version = "1", optional = true }
jql = { version = "4.0", default-features = false, optional = true }
log = "0.4"
mimalloc = { version = "0.1", default-features = false, optional = true }
mlua = { version = "0.7", features = ["lua54", "vendored"], optional = true }
once_cell = { version = "1.10", optional = true }
pyo3 = { version = "0.16", features = [
    "abi3-py38",
    "auto-initialize",
], optional = true }
qsv-dateparser = "0.2"
qsv-stats = "0.3"
qsv_currency = { version = "0.5", optional = true }
rand = "0.8"
rayon = "1.5"
regex = "1"
reqwest = { version = "0.11", features = [
    "blocking",
    "brotli",
    "cookies",
    "gzip",
    "rustls-tls",
], default-features = false }
reverse_geocoder = { version = "3", optional = true }
ryu = "1"
self_update = { version = "0.29", features = [
    "archive-zip",
    "compression-zip-deflate",
    "rustls",
], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
strsim = { version = "0.10", optional = true }
tabwriter = "1.2"
test-data-generation = { version = "0.3", optional = true }
thiserror = { version = "1.0", optional = true }
thousands = "0.2"
threadpool = "1.8"
titlecase = { version = "1", optional = true }
uuid = { version = "1", features = ["v4"] }
vader_sentiment = { version = "0.1", optional = true }
whatlang = { version = "0.14", optional = true }

[dev-dependencies]
actix-governor = "0.3"
actix-web = { version = "4.0", default-features = false, features = [
    "compress-brotli",
    "compress-gzip",
] }
assert-json-diff = "2.0"
quickcheck = { version = "1", default-features = false }
redis = { version = "0.21", default-features = false }
serial_test = "0.6"

[patch.crates-io]
calamine = { git = "https://github.com/jqnatividad/calamine", rev = "c3a00ffdc48201195102e3904758ed62e0af37ea" }
csv = { git = "https://github.com/jqnatividad/rust-csv", branch = "perf-tweaks" }
csv-core = { git = "https://github.com/jqnatividad/rust-csv", branch = "perf-tweaks" }
csv-index = { git = "https://github.com/jqnatividad/rust-csv", branch = "perf-tweaks" }
docopt = { git = "https://github.com/jqnatividad/docopt.rs", branch = "perf-clippy-2021" }
grex = { git = "https://github.com/pemistahl/grex", rev = "9dea3b421d1d27a7dc10ad1a8a81e44eac5ebd1d" }
redis = { git = "https://github.com/mitsuhiko/redis-rs", rev = "b8eb47303c5728e943b914cd10dc35d1fceee05c" }
reqwest = { git = "https://github.com/seanmonstar/reqwest", rev = "5d8bf830cbce552075d9bd03f09644469533b50e" }

[features]
default = ["mimalloc"]
apply = [
    "cached",
    "censor",
    "chrono",
    "dynfmt",
    "eudex",
    "once_cell",
    "qsv_currency",
    "reverse_geocoder",
    "strsim",
    "titlecase",
    "vader_sentiment",
    "whatlang",
]
fetch = [
    "cached",
    "dynfmt",
    "governor",
    "jql",
    "jsonxf",
    "once_cell",
    "thiserror",
]
foreach = []
generate = ["test-data-generation"]
lite = []
lua = ["mlua"]
python = ["pyo3"]
