[package]
name = "xsv"
version = "0.7.0"
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "A high performance CSV command line toolkit."
documentation = "http://burntsushi.net/rustdoc/xsv/"
homepage = "https://github.com/BurntSushi/xsv"
repository = "https://github.com/BurntSushi/xsv"
readme = "README.md"
keywords = ["csv", "tsv", "slice", "command"]
license = "Unlicense"

[[bin]]
name = "xsv"
test = false
bench = false
doctest = false

[[test]]
name = "tests"

[profile.release]
opt-level = 3
lto = true

[profile.test]
opt-level = 2

[dependencies]
csv = "*"
streaming-stats = "*"
tabwriter = "*"
docopt = "*"
quickcheck = "*"

# [dependencies.csv]
# path = "/home/andrew/data/projects/rust/csv"
# git = "git://github.com/BurntSushi/rust-csv"

# [dependencies.streaming-stats]
# path = "/home/andrew/data/projects/rust/rust-stats"
# git = "git://github.com/BurntSushi/rust-stats"
#
# [dependencies.tabwriter]
# path = "/home/andrew/data/projects/rust/tabwriter"
# git = "git://github.com/BurntSushi/tabwriter"
#
# [dependencies.docopt]
# path = "/home/andrew/data/projects/rust/docopt"
# git = "git://github.com/docopt/docopt.rs"
#
# [dev-dependencies.quickcheck]
# path = "/home/andrew/data/projects/rust/quickcheck"
# git = "git://github.com/BurntSushi/quickcheck"
