[package]
name = "xcsv"
version = "0.1.0"
authors = ["Andrew Gallant <jamslam@gmail.com>"]

[dependencies.rust-csv]
# path = "/home/andrew/data/projects/rust-csv" 
git = "git://github.com/BurntSushi/rust-csv"

[dependencies.tabwriter]
git = "git://github.com/BurntSushi/tabwriter"

# [dependencies.docopt] 
# path = "/home/andrew/data/projects/docopt.rs" 

[dependencies.docopt_macros]
# path = "/home/andrew/data/projects/docopt.rs/docopt_macros" 
git = "git://github.com/docopt/docopt.rs"

