# NOTE: some options require nightly, i.e.:
# cargo +nightly fmt
# see https://rust-lang.github.io/rustfmt/ for more info
comment_width                = 100
wrap_comments                = true
format_strings               = true
reorder_impl_items           = true
group_imports                = "StdExternalCrate"
imports_granularity          = "Crate"
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
match_block_trailing_comma   = true
