name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: qsv
            asset_name: qsv-linux.zip
          - os: windows-latest
            artifact_name: qsv.exe
            asset_name: qsv-windows.zip
          - os: macos-latest
            artifact_name: qsv
            asset_name: qsv-macos.zip

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: zip-files
      run: 7z a -tzip target/release/${{ matrix.asset_name }} target/release/${{ matrix.artifact_name }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.asset_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
