name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4.3.1
      with:
        python-version: '3.11'
    - name: Update Rust
      run: rustup update
    - name: Setup Rust-cache
      uses: Swatinem/rust-cache@v2
      with:
        key: qsv-cache
    - name: make empty DLLs directory to prevent spurious python warning
      run: |
        mkdir DLLs   
    - name: Run tests
      run: cargo test --verbose --locked --features=apply,fetch,foreach,generate,luau,python,full
