name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Update Rust
      run: rustup update
    - name: Build
      run: cargo build --verbose --locked --all-features
    - name: Run tests
      run: cargo test --verbose --locked --all-features
