name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: PYO3_PRINT_CONFIG=1 cargo build --verbose --all-features
    - name: Run tests
      run: PYO3_PRINT_CONFIG=1 cargo test --verbose --all-features
