name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ci-linux-tests-${{ github.ref }}-1
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: apt-get update Ubuntu
      run: |
        sudo apt-get update
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4.6.1
      with:
        python-version: '3.11'
    - name: Install and Run Redis
      run: |
        sudo apt-get install redis-server
        sudo service redis-server start
    - name: Update Rust
      run: rustup update
    - name: Setup Rust-cache
      uses: Swatinem/rust-cache@v2
      with:
        key: qsv-cache
    - name: Run tests
      run: cargo test --verbose --locked --features=apply,fetch,foreach,generate,luau,python,polars,feature_capable
