name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive    
    - name: Build
      env: PYO3_PRINT_CONFIG=1 
      run: cargo build --verbose --all-features
    - name: Run tests
      env: PYO3_PRINT_CONFIG=1 
      run: cargo test --verbose --all-features
