name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3.1.1
      with:
        python-version: '3.8'
    - name: Install and Run Redis
      run: |
        sudo apt-get install redis-server
        sudo service redis-server start
    - name: Update Rust
      run: rustup update
    - name: Setup Rust-cache
      uses: Swatinem/rust-cache@v1
      with:
        key: qsv-cache
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Clippy Check
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings        
    - name: Run tests
      run: cargo test --verbose --locked --features=apply,fetch,foreach,generate,lua,python
