name: Rustfmt

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Make doubly sure to install the nightly rustfmt
      run: |
        rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        toolchain: nightly
        use-cross: false
        args: -- --check
